### ISSUE TITLE
Did you load the parameters of vgg19 without the part of fc ?

### ISSUE THREAD

**Issue by wuyang556** [SharifAmit/DilatedFCNSegmentation#9]

**Comment by wuyang556** [comment]
@SharifAmit

**Comment by SharifAmit** [comment]
If you check the file https://github.com/SharifAmit/DilatedFCNSegmentation/blob/master/surgery.py and function "transplant" you will notice that we are transferring weights by copying matching parameters, coercing parameters of  incompatible shape, and dropping unmatched parameters in respect to layers of the models. 

Also it details how and why we are doing that. Since we are converting the model to a Fully convolutional architecture it is necessary that all fully connected layers are converted to convolutional ones.

"The coercion is useful to convert fully connected layers to their equivalent convolutional layers, since the weights are the same and only the shapes are different.  In particular, equivalent fully connected and convolution layers have shapes O x I and O x I x H x W respectively for O outputs channels, I input channels, H kernel height, and W kernel width."

The surgery.py also uses "interp" and "upsample_filt" function to plant the Bilinear Weights as intializers for upsampling layers and also creates all the necessary layers after the "fc7" layer. Notice that in line 30 in "solvesurgery.py" we are running it for 1 iteration so that we can save the newly created model's weight and architecture information as .caffemodel. So that we can load that for training for different Semantic Segmentation task.

Hope this answers your question !

**Comment by wuyang556** [comment]
Thanks for your reply，I notice you replace the fc6 layer of VGG19 with a dilated convolution which is not a tradictional convolution. In FCN8s, the fc6 weights is 4096x512x7x7, while this corresponding dialted convolution weight is 4096x512x3x3, each other is not matched. So in survey.py, the function transplant discard some not matched parameters.

**Comment by SharifAmit** [comment]
Yes, that's right. The dilated convolution has the same receptive field of a 7x7 which is the same as the vanilla convolution of same size. So the parameter decreases many folds making the architecture's total number of parameters 1/3 of the regular FCN architecture.
